---
# tasks file for portainer
- name: Install docker SDK 
  pip:
    name: docker 

- name: Create a volume
  docker_volume:
    name: "{{ portainer_v }}"

- name: Run portainer 
  docker_container:
    name: portainer
    image: "{{ portainer_image }}"
    restart_policy: always
    ports:
    - "{{ host_port }}:{{ container_port }}" # Publish container port 9000 on host port 9888
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - "{{ portainer_v }}:/data"